apiVersion: skaffold/v2beta26
kind: Config
profiles:
- name: test
  deploy:
   helm:
    releases: 
    - name: test
      chartPath: helm/project
      valuesFiles:
        - helm/project/values.yaml
