apiVersion: skaffold/v2beta26
kind: Config
profiles:
- name: test
  deploy:
   helm:
    releases: 
    - name: test
      chartPath: helm/project
      namespace: test
      valuesFilePath:
        - helm/project/values.yaml
        - helm/project/values2.yaml
        - helm/project/values3.yaml
